export { default as HomePage } from './Home';
export { default as WomenPage } from './Women';
export { default as MenPage } from './Men';
export { default as SalePage } from './Sale';
export { default as AboutPage } from './About'; 
export { default as SigninPage } from './Signin'; 
export { default as RegisterPage } from './Register'; 
export { default as ManageProductsPage } from './ManageProducts'; 
export { default as ProductPage } from './Product'; 